# Generated by Django 3.0.8 on 2020-07-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(default='코린이', max_length=120),
        ),
    ]
